"""Per-browser workspace identity.

Each browser generates a random id and sends it on every request. The id
separates watchlists so two people opening the same URL don't edit each
other's; it is deliberately *not* a security boundary — anyone holding an id
can read that watchlist. Only watchlists are scoped. Prices, fundamentals and
Fed summaries stay global, so a second visitor costs no extra API calls.
"""

import re

from fastapi import Header

from app.db import DEFAULT_SPACE

SPACE_HEADER = "X-Vantage-Space"
# Ids are generated by the client, so treat them as untrusted input: bound the
# length and the alphabet before they reach a query.
VALID_SPACE = re.compile(r"^[A-Za-z0-9_-]{1,64}$")


def normalise_space(raw: str | None) -> str:
    """Return a safe space id, falling back to the shared default."""
    if not raw:
        return DEFAULT_SPACE
    raw = raw.strip()
    return raw if VALID_SPACE.match(raw) else DEFAULT_SPACE


async def current_space(x_vantage_space: str | None = Header(default=None)) -> str:
    """FastAPI dependency resolving the caller's workspace."""
    return normalise_space(x_vantage_space)
