import { useState } from "react";
import { ComparisonPage } from "./pages/ComparisonPage";
import { DashboardPage } from "./pages/DashboardPage";
import { FedTrackerPage } from "./pages/FedTrackerPage";

type Tab = "dashboard" | "comparison" | "fed";

const TABS: { id: Tab; label: string }[] = [
  { id: "dashboard", label: "Dashboard" },
  { id: "comparison", label: "Compare" },
  { id: "fed", label: "Fed Tracker" },
];

function App() {
  const [tab, setTab] = useState<Tab>("dashboard");

  return (
    <div className="app">
      <header className="app-header">
        <div className="brand">
          <img src="/favicon.svg" alt="" className="brand-mark" />
          <h1>Vantage</h1>
        </div>
        <nav>
          {TABS.map((t) => (
            <button
              key={t.id}
              className={tab === t.id ? "active" : ""}
              onClick={() => setTab(t.id)}
            >
              {t.label}
            </button>
          ))}
        </nav>
      </header>

      <main>
        {tab === "dashboard" && <DashboardPage />}
        {tab === "comparison" && <ComparisonPage />}
        {tab === "fed" && <FedTrackerPage />}
      </main>

      <footer className="app-footer">
        <p>
          Vantage is a personal research tool. Data from Financial Modeling Prep; Fed
          summaries generated by Claude. Nothing here is investment advice.
        </p>
      </footer>
    </div>
  );
}

export default App;
