import { useCallback, useEffect, useState } from "react";
import { AccountProvider } from "./AccountContext";
import { AccountMenu } from "./components/AccountMenu";
import { ComparisonPage } from "./pages/ComparisonPage";
import { DashboardPage } from "./pages/DashboardPage";
import { FedTrackerPage } from "./pages/FedTrackerPage";
import { useAccount } from "./useAccount";
import { THEMES, useTheme, type Theme } from "./useTheme";

type Tab = "dashboard" | "comparison" | "fed";

const TABS: { id: Tab; label: string }[] = [
  { id: "dashboard", label: "Dashboard" },
  { id: "comparison", label: "Compare" },
  { id: "fed", label: "Fed Tracker" },
];

const TAB_STORAGE_KEY = "vantage.tab";

const THEME_LABEL: Record<Theme, string> = {
  system: "Auto",
  light: "Light",
  dark: "Dark",
};

const THEME_ICON: Record<Theme, string> = {
  system: "◐",
  light: "☀",
  dark: "☾",
};

/**
 * The token from an emailed sign-in link.
 *
 * The link points at the app rather than the API so the cookie is set from a
 * normal page visit. It is stripped from the address bar once read, so a
 * shared or bookmarked URL never carries a live token.
 */
function readSignInToken(): string | null {
  try {
    return new URLSearchParams(window.location.search).get("token");
  } catch {
    return null;
  }
}

function clearSignInToken() {
  try {
    const url = new URL(window.location.href);
    url.searchParams.delete("token");
    window.history.replaceState({}, "", `${url.pathname}${url.search}${url.hash}`);
  } catch {
    /* the token just stays in the address bar */
  }
}

function readStoredTab(): Tab {
  try {
    const stored = localStorage.getItem(TAB_STORAGE_KEY);
    if (TABS.some((t) => t.id === stored)) return stored as Tab;
  } catch {
    /* storage unavailable */
  }
  return "dashboard";
}

function App() {
  const [tab, setTab] = useState<Tab>(readStoredTab);
  const [theme, setTheme] = useTheme();
  const { account, refresh, signOut } = useAccount();
  const [signInToken, setSignInToken] = useState<string | null>(readSignInToken);

  // Switching account changes whose lists the pages should be showing, so they
  // are remounted rather than left holding the previous owner's data.
  const identity = account.signed_in ? (account.email ?? "account") : "anonymous";

  const handleTokenHandled = useCallback(() => {
    setSignInToken(null);
    clearSignInToken();
  }, []);

  // Reopening on the tab you left is worth more than always landing on the
  // dashboard, especially while the Fed tracker is being checked repeatedly.
  useEffect(() => {
    try {
      localStorage.setItem(TAB_STORAGE_KEY, tab);
    } catch {
      /* preference just won't persist */
    }
  }, [tab]);

  function cycleTheme() {
    setTheme(THEMES[(THEMES.indexOf(theme) + 1) % THEMES.length]);
  }

  return (
    <div className="app">
      <header className="app-header">
        <div className="brand">
          <img src="/favicon.svg" alt="" className="brand-mark" />
          <h1>Vantage</h1>
        </div>

        <div className="header-actions">
          <nav>
            {TABS.map((t) => (
              <button
                key={t.id}
                className={tab === t.id ? "active" : ""}
                onClick={() => setTab(t.id)}
                aria-current={tab === t.id ? "page" : undefined}
              >
                {t.label}
              </button>
            ))}
          </nav>

          <AccountMenu
            account={account}
            onSignedIn={refresh}
            onSignOut={signOut}
            pendingToken={signInToken}
            onTokenHandled={handleTokenHandled}
          />

          <button
            className="theme-toggle"
            onClick={cycleTheme}
            title={`Theme: ${THEME_LABEL[theme]} — click to change`}
            aria-label={`Theme: ${THEME_LABEL[theme]}. Click to change.`}
          >
            <span aria-hidden="true">{THEME_ICON[theme]}</span>
          </button>
        </div>
      </header>

      <AccountProvider value={account}>
        <main key={identity}>
          {tab === "dashboard" && <DashboardPage />}
          {tab === "comparison" && <ComparisonPage />}
          {tab === "fed" && <FedTrackerPage />}
        </main>
      </AccountProvider>

      <footer className="app-footer">
        <p>
          Vantage is a personal research tool. Data from Financial Modeling Prep; Fed
          summaries generated by Claude. Nothing here is investment advice.
        </p>
        <p className="footer-note">
          {account.signed_in
            ? `Saved to ${account.email}, so your watchlist follows you to any device.`
            : "Your watchlist is stored against this browser. Sign in to keep it on every device, or use Backup on the dashboard to save a copy."}
        </p>
      </footer>
    </div>
  );
}

export default App;
