import { useEffect, useState } from "react";
import { ComparisonPage } from "./pages/ComparisonPage";
import { DashboardPage } from "./pages/DashboardPage";
import { FedTrackerPage } from "./pages/FedTrackerPage";
import { THEMES, useTheme, type Theme } from "./useTheme";

type Tab = "dashboard" | "comparison" | "fed";

const TABS: { id: Tab; label: string }[] = [
  { id: "dashboard", label: "Dashboard" },
  { id: "comparison", label: "Compare" },
  { id: "fed", label: "Fed Tracker" },
];

const TAB_STORAGE_KEY = "vantage.tab";

const THEME_LABEL: Record<Theme, string> = {
  system: "Auto",
  light: "Light",
  dark: "Dark",
};

const THEME_ICON: Record<Theme, string> = {
  system: "◐",
  light: "☀",
  dark: "☾",
};

function readStoredTab(): Tab {
  try {
    const stored = localStorage.getItem(TAB_STORAGE_KEY);
    if (TABS.some((t) => t.id === stored)) return stored as Tab;
  } catch {
    /* storage unavailable */
  }
  return "dashboard";
}

function App() {
  const [tab, setTab] = useState<Tab>(readStoredTab);
  const [theme, setTheme] = useTheme();

  // Reopening on the tab you left is worth more than always landing on the
  // dashboard, especially while the Fed tracker is being checked repeatedly.
  useEffect(() => {
    try {
      localStorage.setItem(TAB_STORAGE_KEY, tab);
    } catch {
      /* preference just won't persist */
    }
  }, [tab]);

  function cycleTheme() {
    setTheme(THEMES[(THEMES.indexOf(theme) + 1) % THEMES.length]);
  }

  return (
    <div className="app">
      <header className="app-header">
        <div className="brand">
          <img src="/favicon.svg" alt="" className="brand-mark" />
          <h1>Vantage</h1>
        </div>

        <div className="header-actions">
          <nav>
            {TABS.map((t) => (
              <button
                key={t.id}
                className={tab === t.id ? "active" : ""}
                onClick={() => setTab(t.id)}
                aria-current={tab === t.id ? "page" : undefined}
              >
                {t.label}
              </button>
            ))}
          </nav>

          <button
            className="theme-toggle"
            onClick={cycleTheme}
            title={`Theme: ${THEME_LABEL[theme]} — click to change`}
            aria-label={`Theme: ${THEME_LABEL[theme]}. Click to change.`}
          >
            <span aria-hidden="true">{THEME_ICON[theme]}</span>
          </button>
        </div>
      </header>

      <main>
        {tab === "dashboard" && <DashboardPage />}
        {tab === "comparison" && <ComparisonPage />}
        {tab === "fed" && <FedTrackerPage />}
      </main>

      <footer className="app-footer">
        <p>
          Vantage is a personal research tool. Data from Financial Modeling Prep; Fed
          summaries generated by Claude. Nothing here is investment advice.
        </p>
        <p className="footer-note">
          Your watchlist is stored against this browser. Clearing site data starts a fresh
          one, and opening the app elsewhere gives you a separate list.
        </p>
      </footer>
    </div>
  );
}

export default App;
